### ISSUE TITLE
Proposal: `showLitChar` (and `show @Char`) shouldn't escape readable Unicode characters

### ISSUE THREAD

**Issue by ksqsf** [haskell/core-libraries-committee#26] opened 2021-12-20 12:29 UTC
# Motivation

Currently, ghci cannot print readable Unicode directly,

```haskell
ghci> 'λ'
'\955'
ghci> "世界"
"\19990\30028"
ghci> '😂'
'\128514'
```

According to the documentation,

- `Show`: "Conversion of values to readable Strings." 

  Escaped strings are often not very readable.

- `showLitChar`: "Convert a character to a string using only printable characters, using Haskell source-language escape conventions. "

  It does not consider Unicode-printable characters at all.

**Conclusion 1**: There's a bug, either in the code, or in the doc.

You might argue that people are using `Show` as a lightweight serialization mechanism, and this proposal will cause unexpected breakage for them. However, this breakage is expected only when they are sending serialized data over network, _assuming ASCII-compatible encodings on both sides_. And there is actually an inconsistency, and your code is probably buggy if you rely on escaping:

```haskell
ghci> data Γ a = Γ a deriving Show
ghci> Γ 'Γ'
Γ '\915'   -- Uh-oh.
```

**Conclusion 2**: If you rely on `Show`'s escaping for encoding-independent serialization today, your code is probably buggy.

Therefore, we have pretty strong reasons to correct the behavior of `showLitChar` (and in turn `show @Char` and `show @String`):

1. It's much friendlier to learners around the globe: you can now use your native language freely in ghci.
2. Fix a longstanding inconsistency issue.
3. Align better with the documentation.
4. `String` is always a list of Unicode code points. Why escape it in the first place? Encoding and decoding is already handled elsewhere.
5. `showLitChar` remains unchanged since 1999, a time when GHC had no good Unicode support. They had reasons to escape then, we don't today.

See also previous discussions at [gitlab](https://gitlab.haskell.org/ghc/ghc/-/issues/20027), [libraries@](https://mail.haskell.org/pipermail/libraries/2021-July/031372.html), [r/haskell](https://www.reddit.com/r/haskell/comments/obx7v2/support_unicode_characters_in_instance_show_string/), and [another proposal](https://github.com/haskell/core-libraries-committee/issues/25).

# Proposed Changes

- Relax `showLitChar` so that readable Unicode characters in `Char` _and_ `String` are not escaped.
- Add a newtype wrapper `Ascii`, and supporting functions to really escape all non-ASCII characters. And `escapeAscii` guarantees that `oldshow x = asciiToString . escapeAscii . newshow $ x` where `x :: String`.

```haskell
newtype Ascii = MkAscii String

escapeAscii :: String -> Ascii
asciiToString :: Ascii -> String
```

- GHCi supports only Unicode-compatible terminals after this proposal is implemented.

# Breakage and Migration

This is a breaking change with a large impact. All libraries with custom `Show` instances will probably need a major version bump, as their `show` now can output different results. However,

1. The new behavior is usually what you and the users really want. Even if the results are different. Maybe you don't need to do anything at all:
    - Existing serialized data will still be supported by `Read`.
    - New serialized data will still be supported by an existing program compiled with an older version of base.
2. If you rely on the old behavior, consider using `asciiToString . escapeAscii` to get the old behavior back:

```haskell
-- Previous
instance Show T where
  show x = _tostring x

-- Now
instance Show T where
  show x = asciiToString . escapeAscii $ _tostring x
```

# Implementation

I will implement this proposal.

**update**: a PoC has been implemented [here](https://gitlab.haskell.org/ksqsf/ghc/-/tree/clc-proposal-26).

**Comment by Bodigrim** [comment] 2021-12-20 22:41
> You might argue that people are using `Show` as a lightweight serialization mechanism

I don't quite follow: how does the proposal impact this use case? Seems users can continue to use `Show` for lightweight all-bets-off serialization?

**Comment by ksqsf** [comment] 2021-12-21 05:06
> I don't quite follow: how does the proposal impact this use case? Seems users can continue to use `Show` for lightweight all-bets-off serialization?

Yes, I'm not arguing they can't. Here, I'm specifically referring to the case where the program is relying on the escaping, so that transmitting a serialized file over network is "reliable".

- A serializes a value in a file using A's local encoding.
- A sends this file to B, and B deserializes this file using B's local encoding.

This is an expected breakage, and indeed there are concerns around it. However, as the example has shown, even today this behavior is not reliable, since data constructors are not at all escaped. Any program that relies on escaping is already buggy, and should move to a better solution. To smooth the migration, they can use the proposed `escapeAscii`, which reliably escapes all non-ASCII characters.

I've edited the proposal to clarify it.

**Comment by Bodigrim** [comment] 2021-12-22 00:02
> Here, I'm specifically referring to the case where the program is relying on the escaping, so that transmitting a serialized file over network is "reliable".
> 
>     * A serializes a value in a file using A's local encoding.
> 
>     * A sends this file to B, and B deserializes this file using B's local encoding.

But this is not reliable even now: imagine that A's local encoding is UTF8, but B's local encoding is UTF16. Any usage of `Show` for serialization requires the same local encoding on both sides; the proposal does not impact it in the slightest.

What about `show` for `String`? Is it intentional to leave it escaped, even while changing `instance Show Char`?

**Comment by ksqsf** [comment] 2021-12-22 02:48
> But this is not reliable even now: imagine that A's local encoding is UTF8, but B's local encoding is UTF16. Any usage of `Show` for serialization requires the same local encoding on both sides; the proposal does not impact it in the slightest.

Indeed! I forgot the existence of multibyte encodings...

> What about `show` for `String`? Is it intentional to leave it escaped, even while changing `instance Show Char`?

Strings will be unescaped, since it's implemented as `Char`'s `showList`. I've edited the proposal.

**Comment by gwils** [comment] 2022-01-03 09:31
I'm in favour of fixing this. I think a lot of newer Haskellers will expect this behaviour, and this will give a better experience for non-English users (of which there are surely many!).
I think the breakage is likely to be acceptable. Relying on `Show`/`Read` for (de)serialisation is something that feels to me like it wouldn't be seriously used by anyone but beginners, and as you've described, it should keep working in most cases except for a rather contrived one.
I'd like to hear counter-arguments here, if anybody has them. Can anyone demonstrate that this breaks anything real?

**Comment by chreekat** [comment] 2022-01-03 17:53
> Relying on Show/Read for (de)serialisation is something that feels to me like it wouldn't be seriously used by anyone but beginners

Every code base I've ever interacted with has fought a (losing) battle with using Show and Read for this purpose. :) Maybe I'm surrounded by beginners, but even so, this comment feels to me like it's trivializing a real phenomenon.

I'm in favor of this change, so I'm commenting in the spirit of avoiding another Eq-of-no-Neq situation.

**Comment by gwils** [comment] 2022-01-06 07:18
>this comment feels to me like it's trivializing a real phenomenon

I apologise; I could have worded that more respectfully.

**Comment by NorfairKing** [comment] 2022-01-12 00:55
+1 as long as the proposal can specify the desired behaviour in these cases:

1. ANSII codes in `String`
2. The `show` instance of `Text`
3. The `show` instance of `ByteString`

**Comment by stephen-smith** [comment] 2022-01-12 01:54
> ANSII codes in String

Neither 027 nor 0177 characters are "readable Unicode characters" so I don't think ANSI would be meaningfully changed by this proposal.

**Comment by ekmett** [comment] 2022-01-12 03:59
So we're proposing to break use of `Show`/`Read` and `ghci` for non-utf8 terminal / codepages? (along with all serialization tests that wrote out data beforehand and are checking golden datasets, and serialization of data with Show from code running on new GHC versions to old?)

If we wanted to make this configurable, there's not really a good way to smuggle knowledge of the surrounding host environment into Show without changing a lot of code, e.g. by adding an argument to showsPrec, diverging further from the standard, or doing something awful like plumbing around a big implicit parameter indicating if we expect to be serializing with unicode, or passing flags to the executable and hoping you don't need to use things with different semantics in different parts of your code. But then if you are going to go that far with settings, adding all sorts of options for indentation and spacing and whether it should use record syntax or not seems to be in order, whereupon it has become a full fledged pretty printing library.

**Comment by ekmett** [comment] 2022-01-12 04:02
The main difference with the Show/Read for a unicode-named type mentioned above is it is often have a lot more control over the data types I show than the contents of the strings users put in them.

**Comment by ksqsf** [comment] 2022-01-12 05:51
Thanks for the feedback. I will try to respond to them based on my current understanding of situations.

> 2. The `show` instance of `Text`

`text` maintainers will have to make their own decisions on whether to keep the old behavior. My expectation is that `text` will eventually be unescaped.

> 3. The `show` instance of `ByteString`

Likewise, it's up to `bytestring` maintainers. My expectation is that `ByteString` will still be 8bit-truncated, so its output will not be affected by this proposal.

> Is there any benefit to this _outside_ of ghci? 

`Show` is used by a lot of Haskell programs, which will likely to benefit from this. E.g., IHP uses `Show` in its admin interface. I agree that perhaps a better solution is to drop `Show` in favor of `text-display`. So this is not really convincing.

> So we're proposing to break use of `Show`/`Read` and `ghci` for non-utf8 terminal / codepages? 

I'm not sure if this is the entire story, but I'd say yes. My understanding is that GHCi and other `String` I/O functions already handle host encodings correctly, as they always consider the external encoding. It's, however, probable that some valid Unicode characters cannot be encoded using the external encoding. (I'm not super familiar with the GHC encoding mechanism so please correct me if I'm wrong here.)

> (along with all serialization tests that wrote out data beforehand and are checking golden datasets, 

Unfortunately, character-by-character comparison will be broken, yes.

> and serialization of data with Show from code running on new GHC versions to old?)

As long as the data is decoded correctly, this use case will not be affected.

**Comment by tomjaguarpaw** [comment] 2022-01-12 13:11
> Is there a way to add another hack to ghci so that we Show in the friendlier way that you propose here?

Yes

```
% cabal repl --build-depends pretty-simple
...
Prelude> :set -interactive-print=Text.Pretty.Simple.pPrint
Prelude> "λ"
"λ"
Prelude> "世界"
"世界"
Prelude> "😂"
"😂"
```

(It doesn't work with `Char` yet, only `String`, but that is an easily-addressed issue.)

I've mentioned this in OP's previous issue reports but he hasn't chosen to list it as an alternative. 

* https://gitlab.haskell.org/ghc/ghc/-/issues/20027#note_362926

* https://github.com/haskell/core-libraries-committee/issues/25#issuecomment-997819577

**Comment by hasufell** [comment] 2022-01-12 17:16
-1

It breaks code (whether we consider using Show/Read for serialization to be a good thing is irrelevant) and doesn't fix any real bug. There are workarounds possible for ghci.

Not worth it.

**Comment by Bodigrim** [comment] 2022-01-13 01:50
> +1 as long as the proposal can specify the desired behaviour in these cases:
> 
>     1. ANSII codes in `String`
>     2. The `show` instance of `Text`
>     3. The `show` instance of `ByteString`

If this proposal is accepted, I'll update `text` and `bytestring` to provide a stable interface independently of GHC version. It's likely to be non-escaping for `text` and always escaping for `bytestring`, but we'll see.

**Comment by Bodigrim** [comment] 2022-01-13 01:57
> Is there any benefit to this _outside_ of ghci?

Of course. If I `traceShow` a data type, containing Unicode characters, why GHC mangles it beyond recognition?

**Comment by hasufell** [comment] 2022-01-13 07:48
> > Is there any benefit to this _outside_ of ghci?
> 
> Of course. If I `traceShow` a data type, containing Unicode characters, why GHC mangles it beyond recognition?

https://hackage.haskell.org/package/pretty-simple-4.0.0.0/docs/Debug-Pretty-Simple.html#v:pTraceShow

Again: solutions exist. There's no reason to break base.

**Comment by Bodigrim** [comment] 2022-01-13 21:11
> Again: solutions exist. There's no reason to break base.

Generally speaking, most of CLC proposals (as opposed to GHC proposals) can be potentially implemented outside of `base`, e. g., in an alternative prelude. This fact alone does not make them automatically undesirable, and neither existence of alternatives or workarounds does. In my opinion these are two different questions: 1) what's the best possible default? and 2) can we afford breaking things to achieve it? I think we are not yet done with the first one here.

I'm grateful to @tomjaguarpaw for proposing an alternative solution, but this facilitates further discussion, not precludes it.

**Comment by hasufell** [comment] 2022-01-14 09:48
> Generally speaking, most of CLC proposals (as opposed to GHC proposals) can be potentially implemented outside of base, e. g., in an alternative prelude. This fact alone does not make them automatically undesirable, and neither existence of alternatives or workarounds does.

Well, the problem is that CLC still hasn't defined clear core principles. I proposed such principles [here](https://github.com/haskell/core-libraries-committee/issues/12#issuecomment-968293690) and according to that categorization, this proposal falls under "ergonomic improvements" (because it's not a bugfix and not a correctness improvement either), which is the weakest category and suggests this should be implemented outside of base.

**Comment by ksqsf** [comment] 2022-04-30 11:47
I appreciate and in general agree with @hasufell 's proposed principles. However, the problem still needs a solution. If we were to reject proposal, the way forward (as I conceive) is probably:

1. Add to base a new function that undoes the escaping in base. (like `pPrint` and `pShow` from pretty-simple). A user can choose whichever print function they prefer without having to install a third-party package first. The merit of adding it to base is, again, it can be more easily used anywhere.
2. Acknowledge and document clearly that `print` and `show` will escape any non-ASCII character. We probably also should document that `Show` shouldn't be used for serialization due to the example mentioned above.

These two changes are backward-compatible. The only downside is probably extra burden for maintainers (though it should be moderate). If everyone is fine with this solution, I'll go ahead and make a patch.

**Comment by Bodigrim** [comment] 2022-05-22 12:55
First of all, I must say that English native speakers gravely underestimate how important is this issue. It is very frustrating when `ghci` refuses to speak your language. 

I do not think that the workaround proposed by @tomjaguarpaw is a complete solution. It requires `cabal`, it requires third-party packages, you must think about it __beforehand__, you cannot apply it in the middle of ghci session. Practically speaking, there are plenty of situations where the proposed workaround is not applicable: a) playgrounds such haskell.org, b) lambdabot, c) iHaskell, d) HLS eval plugin, e) haddocks. Here is a real world example where one must choose either readable examples, or working doctest: https://hackage.haskell.org/package/text-rope-0.1/docs/Data-Text-Lines.html#v:splitAt

**Comment by tomjaguarpaw** [comment] 2022-05-22 13:25
I am conscious that as a speaker of a language whose character set fits into ASCII I am at risk of underestimating how important this issue is. Yet I don't think I have, actually, fallen into that trap. (I may be mistaken.) Furthermore, others who have commented against this proposal are native speakers of languages whose character sets don't fit in ASCII.

To be clear, I am not against this proposal per se. I am fully in support of migrating our ecosystem to become unicode-aware and inclusive of speakers of all languages. I am against proceeding with a proposal like this *until all other alternatives to breaking base have been exhausted*.  The proposal author not having incorporated my workaround into any of his proposals, on this issue tracker, or on GHC gitlab, raises concern in me. Even if one believes that my workaround is insufficient it is good practice to state it clearly upfront so that it can play a full role in the debate, even if that role is to be dismissed be a strong contrary argument.

My responses regarding the `Text.Pretty.Simple` workaround:

> I do not think that the workaround proposed by @tomjaguarpaw is a complete solution. It requires cabal

It does not require cabal. It only requires you to make `Text.Pretty.Simple` known to ghci. As a user of cabal I chose to demonstrate the cabal method because I am familiar with it. Similar methods will exist for stack and bare ghci (though I don't use them so I don't know what they are).

> it requires third-party packages

It does, but I'm not sure I see why that is a problem. Despite being cautious about changing the behaviour of `Read` and `Show`, I'm not opposed to adding a unicode-aware *alternatives* to base.

> you must think about it beforehand, you cannot apply it in the middle of ghci session

Sure you can.

```
$ cabal repl --build-depends pretty-simple
...
Prelude> "λ"
"\955"
Prelude> :set -interactive-print=Text.Pretty.Simple.pPrint
Prelude> "λ"
"λ"
```

If `Text.Pretty.Simple` wasn't known to ghci at startup then this won't work, but this is a wider problem with ghci/cabal (perhaps stack too?) that deserves a wider fix.

> Practically speaking, there are plenty of situations where the proposed workaround is not applicable: a) playgrounds such haskell.org, b) lambdabot, c) iHaskell, d) HLS eval plugin, e) haddocks

I'm not sure why the workaround isn't applicable to haskell.org. Indeed I don't see why playgrounds and the other tools you mention shouldn't use a unicode-aware *alternative* to `Read`/`Show`. Is there something about them that *requires* `Read`/`Show` and prevents them being switched to use an alternative?

> Here is a real world example where one must choose either readable examples, or working doctest

Even doctest could be changed to use `Text.Pretty.Simple`!

**Comment by Kleidukos** [comment] 2022-06-26 10:26
A little bit late to the party, but here is a real and concrete consequence of our inability to print human-readable Unicode characters:

https://gitlab.haskell.org/ghc/ghc/-/issues/21769

![Screenshot 2022-06-21 at 20-44-58 Movie](https://user-images.githubusercontent.com/29253044/175809914-0c27e41b-098a-4da1-86a4-5aac265f8f80.png)

**Comment by tomjaguarpaw** [comment] 2022-06-26 11:20
I'm not sure I see the connection, other than indirectly.  Haddock could choose any function it likes to convert type declarations to HTML. Why doesn't it choose a Unicode-aware one? For example, it has put `Move` in bold, even though `show` doesn't do that!

**Comment by Kleidukos** [comment] 2022-06-26 11:41
@tomjaguarpaw The ticket shows that the problem is at GHC's root, with [pprIfaceTyLit](https://gitlab.haskell.org/ghc/ghc/-/blob/master/compiler/GHC/Iface/Type.hs#L1704-1707)

**Comment by tomjaguarpaw** [comment] 2022-06-26 11:53
I still don't see the connection to this issue.  It seems at least two steps removed.

1. Haddock is welcome to use any function it wants to generate its HTML files. It doesn't have to use `pprIfaceTyLit`! 
2. `pprIfaceTyLit` is nonethess wrong because it doesn't serialise the type name as it would actually occur in a source file, i.e. to Unicode. The appropriate fix seems to be to change `pprIfaceTyLit`.

**Comment by hasufell** [comment] 2022-06-26 11:54
Yes, I think the original issue was about GHCi. Let's not add haddock to the topic, otherwise this will derail in scope.

**Comment by tomjaguarpaw** [comment] 2022-07-15 08:58
For those, like me, saw the email notification of Jens's original message, I think it's important to point out that ghci *can* show Unicode out of the box:

```haskell
> newtype S = S String
> instance Show S where show (S s) = s
> S "λ世界😂"
λ世界😂
```

This proposal is indeed about changing the behaviour of `Show`. Change to ghci default behaviour is merely one of the purported benefits.

**Comment by xogcox** [comment] 2022-08-06 09:23
## Suggested workaround

I would like to suggest another workaround for `show` and `print`. The basic idea is to have a function `unescape :: String -> String` that takes the output of `show`, finds the escape codes and replaces them with literal characters where appropriate. Then versions of `show` and `print` can be defined as:

```haskell
show' = unescape . show
print' = putStrLn . unescape . show
```

This approach has the following advantages:

* It can be implemented as a standalone module, without requiring any changes to `base`

* It has minimal dependencies -- it can be implemented using only functions from `base`

* It can provide the same guarantee as the original `show` about round-tripping with `read` -- that is, `read . unescape . show == id` whenever `read . show == id`.

In particular, I think this solution matches the original proposal more closely than the functions from `pretty-simple`. The main purpose of `pretty-simple` is pretty-printing, including line splitting and indentation, so its use cases do not overlap completely with those of the `show` function.

The only downside to the above workaround I can see is that it replaces character sequences that accidentally happen to be escape codes, but this is probably not too bad, since it should not happen with built-in or automatically derived instances of `show`.

## My implementation

Here is my [implementation of the above suggestion](https://github.com/xogcox/show-unescaped). It is meant to be built upon, amended or replaced as necessary, not as a perfect final version. For one thing, the naming of the functions is not that great, and I'm not sure whether the range of options offered is ideal either.

## Motivation and comments on procedural matters

I decided to make this suggestion in the hope of contributing to progress on this proposal.

Any change to the output of `show` and related functions is inevitably a large breaking change that potentially inconveniences a large number of people. Right now, I don't think the demand for a change is great enough to justify the inconvenience that may be caused. So, for the moment, I think finding a good workaround is the best solution.

On the other hand, I'd like the door to be kept open to accepting the proposal in the future. It'd be disappointing to be told "we agreed on a workaround, and that ought to be good enough. This issue is closed -- don't bring it up again." Perhaps, if a consensus on the best workaround can be reached, it can receive official endorsement or even added to `base` as an additional function? If in the future a workaround becomes widely adopted, there would then be a stronger case for a breaking change as in the proposal.

I think this scenario would give supporters of the proposal more incentive to find a workaround, rather than insisting on a change to `base` right away. Of course, it doesn't have to be my implementation above. I strongly encourage people to provide better alternatives!

## Ending comment

I hope this was helpful and not too long or unclear. Thank you for reading!

**Comment by Bodigrim** [comment] 2022-08-15 19:30
Re https://github.com/haskell/core-libraries-committee/issues/26#issuecomment-1133896206. Yes, ignoring non-negligible amount of friction, we can apply the workaround with `:set -interactive-print=Text.Pretty.Simple.pPrint` in all interactive environments. But if we agree that it makes sense to apply it everywhere, it means that non-escaped Unicode is just a better default. 

Moreover, I personally want this change to happen in non-interactive environments too. As a person, who spends considerable amount of time debugging Unicode intricacies in `text`, I find output like in https://github.com/haskell/text/issues/462 extremely unhelpful:

          t_toCaseFold_char:                                  FAIL
            *** Failed! Falsified (after 95 tests and 1 shrink):
            '\43953'
            "\5089" /= "\43953"
            Use --quickcheck-replay=356345 to reproduce.
            Use -p '/t_toCaseFold_char/' to rerun this test only.

Essentially GHC defaults to the worst possible alternative. If it displayed Unicode characters proper, I'd instantly recognise the relationship between them. If it escaped Unicode symbols using hex numbers, I'd be able to google them easily. But decimal representation?.. That's complete nonsense.

**Comment by tomjaguarpaw** [comment] 2022-08-15 19:48
I would suggest that your test framework attempt to address that problem first. If that proves impossible for some reason, then we can think about converting over the entire ecosystem as an alternative.

**Comment by Bodigrim** [comment] 2022-08-22 19:25
> I would suggest that your test framework attempt to address that problem first. If that proves impossible for some reason, then we can think about converting over the entire ecosystem as an alternative.

Sure, with a great deal of effort I can wrap every `Char`, `String` and `Text` into a newtype with an improved `instance Show`. But it simply enforces argument that non-escaped Unicode is just a better default.

I don't buy that this is a noticable breaking change. If someone used `show` to serialise data (which is arguably wrong), they still can deserialise it back with `read`, no matter of escaping.

**Comment by tomjaguarpaw** [comment] 2022-08-22 20:24
> I don't buy that this is a noticable breaking change.

You may be right. If so then I am in support of it. It is better in every other dimension as far as I can see[^1]. I believe the CLC gold standard is an impact assessment. Do we have a volunteer to perform one?

[^1]: Although I'd like some reassurance we aren't breaking people with non-Unicode-aware terminals.

**Comment by hasufell** [comment] 2022-08-22 23:44
> 
> I don't buy that this is a noticable breaking change. If someone used `show` to serialise data (which is arguably wrong), they still can deserialise it back with `read`, no matter of escaping. 

Golden tests and hardcoded tests are a common use case for Show. These will definitely break.

**Comment by Bodigrim** [comment] 2022-08-22 23:53
Potentially, in rare cases when such tests involve Unicode, but this kind of breakage does not affect library components or executables, they'll continue to work well.

**Comment by hasufell** [comment] 2022-08-22 23:59
Sure. I just think that reasoning about breakage is really hard. Either we believe PVP works or we don't.

Assessing potential impact always runs the chance of missing something that will only be visible in some proprietary codebase.

**Comment by Bodigrim** [comment] 2022-09-17 18:04
@ksqsf I’m sorry for an extremely long wait. Are you still interested to champion the proposal?

**Comment by Bodigrim** [comment] 2022-11-15 00:11
I'm very bullish on this proposal, but I don't have time to champion it myself. So unless someone is willing to takeover after @ksqsf, I'll close as abandoned in two weeks.

**Comment by ulysses4ever** [comment] 2022-11-15 05:49
@Bodigrim what's left for it in your view? "Simply" an implementation (that can be voted on) or more litigation, impact assessment, etc.?

**Comment by Bodigrim** [comment] 2022-11-15 21:52
@ulysses4ever hard to tell. We've had unsatisfactory experience with proposals, which were abandoned by original authors and someone was kind enough to write an implementation, but then more details and questions emerged, and no one was enthusiastic enough to answer them. 

The expectation is that a proposer is keen to see their proposal through, which includes but is not limited to preparing an MR. This might involve a good deal of bikeshedding and heated discussions.

This proposal currently lacks a plan for a wider ecosystem beyond `base`. What happens to `instance Show` for `ByteString`? `ShortByteString`? `Text`? `ShortText`? What happens to things like `gshow` from `syb`? What happens to `text-show` package? Are there ways to ensure that `ghci` operates in Unicode-compatible mode? Is it problematic on Windows?

**Comment by Bodigrim** [comment] 2022-11-27 22:55
> GHCi supports only Unicode-compatible terminals after this proposal is implemented.

If someone picks up the proposal, this point requires a more detailed impact assessment. 

For instance, is it harmless on Windows? I remember that terminals on Windows 7 used to be in non-Unicode mode by default. Did it get any better in Windows 10? 

I've also seen plenty of Docker images, configured by default with en_US locale. Admittedly, you are not expected to run interactive sessions there, but probably GHCi would need to run `canUseUnicode` from `GHC.Driver.Session`:
```haskell
 canUseUnicode <- do let enc = localeEncoding
                         str = "‘’"
                     (withCString enc str $ \cstr ->
                          do str' <- peekCString enc cstr
                             return (str == str'))
                         `catchIOError` \_ -> return False
```

**Comment by Bodigrim** [comment] 2022-11-29 00:17
Closing as abandoned. Happy to reopen if someone is serious to take over.

**Closed by Bodigrim** 2022-11-29 00:17 UTC

**Comment by balazs-endresz** [comment] 2023-03-08 20:40
There's another even more convenient workaround to show unicode strings:

```hs
instance {-# OVERLAPPING #-} Show String where
  show x = '"' : x ++ "\""
```

Apologoies if this isn't the best place but I haven't seen this mentioned anywhere before, so thought might be worth pointing it out.

A related ghc ticket talks about the Show instance of String: https://gitlab.haskell.org/ghc/ghc/-/issues/20027 but I guess there might be an instance only for Char and List, so one can be more specific with [Char]/String.

This works in ghci, and on the Haskell Playground too: https://play.haskell.org/saved/WjWq8fb4 (staring from ghc 9.2)

I don't know what problems it might cause but seems to be good enough for simpler use cases at least.
